#!/bin/bash

# ─────────────────────────────────────────────────────────
# FinanceFlow - Guía de Despliegue
# ─────────────────────────────────────────────────────────
# Uso: bash scripts/deploy.sh
# ─────────────────────────────────────────────────────────

echo "==========================================================="
echo "  🌍 FinanceFlow - Guía de Despliegue"
echo "==========================================================="
echo ""
echo "Sigue estos pasos EN ORDEN para desplegar la aplicación:"
echo ""
echo "───────────────────────────────────────────────────────────"
echo "  PASO 1: Crear Base de Datos en Neon"
echo "───────────────────────────────────────────────────────────"
echo "  1. Ve a https://console.neon.tech"
echo "  2. Regístrate (plan Free)"
echo "  3. Crea un proyecto 'financeflow'"
echo "  4. Copia la cadena de conexión (DATABASE_URL)"
echo ""
echo "───────────────────────────────────────────────────────────"
echo "  PASO 2: Crear repositorio en GitHub"
echo "───────────────────────────────────────────────────────────"
echo "  1. Ve a https://github.com/new"
echo "  2. Crea un repositorio (público o privado)"
echo "  3. En tu terminal:"
echo "     git init"
echo "     git add ."
echo "     git commit -m \"Initial commit\""
echo "     git branch -M main"
echo "     git remote add origin https://github.com/TU_USER/financeflow.git"
echo "     git push -u origin main"
echo ""
echo "───────────────────────────────────────────────────────────"
echo "  PASO 3: Desplegar Backend en Render"
echo "───────────────────────────────────────────────────────────"
echo "  1. Ve a https://dashboard.render.com"
echo "  2. Conecta tu cuenta de GitHub"
echo "  3. Crea un 'New Web Service' → selecciona el repo"
echo "  4. Render detectará automáticamente render.yaml"
echo "     O configura manualmente:"
echo "     - Name: financeflow-api"
echo "     - Root Directory: backend"
echo "     - Build Command: npm install && npx prisma generate && npm run build"
echo "     - Start Command: npm run start:prod"
echo "     - Plan: Free"
echo "  5. Agrega variables de entorno:"
echo "     - DATABASE_URL: (cadena de Neon)"
echo "     - JWT_SECRET: (generar uno seguro)"
echo "     - CORS_ORIGIN: https://financeflow.vercel.app"
echo "  6. Crea una Base de Datos PostgreSQL en Render (o usa Neon)"
echo "  7. Haz clic en 'Create Web Service'"
echo ""
echo "───────────────────────────────────────────────────────────"
echo "  PASO 4: Desplegar Frontend en Vercel"
echo "───────────────────────────────────────────────────────────"
echo "  1. Ve a https://vercel.com/new"
echo "  2. Conecta tu cuenta de GitHub"
echo "  3. Selecciona el repositorio"
echo "  4. Vercel detectará automáticamente Vite"
echo "  5. Configura:"
echo "     - Root Directory: frontend"
echo "     - Framework Preset: Vite"
echo "     - Build Command: npm run build"
echo "     - Output Directory: dist"
echo "  6. Agrega variable de entorno:"
echo "     - VITE_API_URL: https://TU_BACKEND.onrender.com/api"
echo "  7. Haz clic en 'Deploy'"
echo ""
echo "───────────────────────────────────────────────────────────"
echo "  🎉 ¡Aplicación desplegada!"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "Enlaces:"
echo "  Frontend: https://financeflow.vercel.app"
echo "  Backend:  https://financeflow-api.onrender.com"
echo "  Health:   https://financeflow-api.onrender.com/api/health"
echo ""
echo "Credenciales demo (después de ejecutar seed):"
echo "  Email:    demo@financeflow.app"
echo "  Password: demo1234"
echo ""
echo "==========================================================="
